#
# Rock R Server Dockerfile with DataSHIELD Dolomite Stadium profile
#
# https://github.com/datashield/docker-rock
#

FROM datashield/rock-base:6.2-R4.2

ENV DSBASE_VERSION 6.1.1

ENV ROCK_LIB /var/lib/rock/R/library

# Install new R packages
RUN Rscript -e "remotes::install_github('datashield/dsBase', ref = '$DSBASE_VERSION', repos = c('https://cloud.r-project.org', 'https://cran.datashield.org'), dependencies = TRUE, upgrade = FALSE, lib = '$ROCK_LIB')"

RUN chown -R rock $ROCK_LIB
